# -- AtomiCloud Service Tree. See [ServiceTree](https://atomicloud.larksuite.com/wiki/OkfJwTXGFiMJkrk6W3RuwRrZs64?theme=DARK&contentTheme=DARK#MHw5d76uDo2tBLx86cduFQMRsBb)
serviceTree:
  platform: &platform sulfoxide
  service: &service zinc
  module: issuer
  layer: "1"

# -- Create SecretStore via secret of secrets pattern
sulfoxide-bromine:
  serviceTree:
    platform: *platform
    service: *service
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
  # -- Store name to create
  storeName: *service
  # -- Secret of Secrets reference
  rootSecret:
    name: *service
    # -- DOPPLER Token Reference
    ref:
      clientId: SULFOXIDE_ZINC_CLIENT_ID
      clientSecret: SULFOXIDE_ZINC_CLIENT_SECRET

# -- Secret Annotations (External Secrets) to control synchronization
secretAnnotation:
  argocd.argoproj.io/sync-wave: "-2"

# -- Dictionary of Issuers to configure, where each key is the name of the issuer, and value is the configuration
issuers:
  letsencrypt:
    # -- Email to notify for the issuer
    email: ernest@eng.atomi.cloud
    # -- Type of Issuer: `ClusterIssuer` or `Issuer`
    type: ClusterIssuer
    # -- ACME compatible server
    server: https://acme-v02.api.letsencrypt.org/directory
    # -- List zones to issue for
    zones:
      - atomi.cloud
    # -- Secret for DNS provider to issue certificate
    secrets:
      # -- Name of the secret
      name: cloudflare-api-token-secret
      # -- Key in the secret to use
      key: api-token
      # -- Internal Secret, use secret propogated via Helm
      internal:
        # -- Enable using internal secret
        enable: false
        # -- The actual secret value
        value: ""
      # -- External Secret, use secret from external secret store
      external:
        # -- Enable using external secret
        enable: true
        # -- Refresh Interval for the external secret
        refreshInterval: 1h
        # -- Remote reference for the secret
        remoteSecretName: CLOUDFLARE_TOKEN
        # -- Secret store to use
        secretStore:
          # -- Name of secret store to use
          name: *service
          # -- Type of Secret Store: `ClusterSecretStore` or `SecretStore`
          kind: SecretStore
        # -- Secret policy
        policy:
          # -- Creation policy
          creation: Owner
          # -- Deletion policy
          deletion: Retain
    # -- TLS Certificate solvers
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
