serviceTree:
  landscape: &landscape pikachu
  cluster: &cluster amber

issuers:
  letsencrypt:
    email: ernest@eng.atomi.cloud
    type: ClusterIssuer
    server: https://acme-v02.api.letsencrypt.org/directory
    zones:
      - atomi.cloud
    secrets:
      name: cloudflare-api-token-secret
      key: api-token
      internal:
        enable: false
      external:
        enable: true
        refreshInterval: 1h
        remoteSecretName: CLOUDFLARE_DNS_TOKEN
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
sulfoxide-bromine:
  serviceTree:
    landscape: *landscape
    cluster: *cluster