version: "3"

env:
  RELEASE_NAME: sulfoxide-zinc

includes:
  entei:opal:
    taskfile: tasks/Taskfile.cluster.yaml
    vars:
      LANDSCAPE: entei
      CLUSTER: opal

tasks:
  # Utility
  start:cluster:
    desc: Starts the playground cluster to test helm charts
    cmds:
      - ./scripts/local/create-k3d-cluster.sh

  stop:cluster:
    desc: Destroys the playground cluster to test helm charts
    cmds:
      - ./scripts/local/delete-k3d-cluster.sh

  # Helm Operations
  update:
    desc: Update Helm dependencies
    dir: chart
    cmds:
      - helm dependency update

  latest:
    desc: Get the latest version of Bromine
    cmds:
      - >-
        echo "sulfoxide-bromine: $(skopeo list-tags docker://ghcr.io/atomicloud/sulfoxide.bromine/sulfoxide-bromine | jq -r '.Tags[]' | sort -V | tail -n 1)"
