{{ range $k, $v := .Values.issuers }}
apiVersion: cert-manager.io/v1
kind: {{ $v.type }}
metadata:
  name: "{{ $.Release.Name }}-{{ $k }}-issuer"
  labels: {{- include "sulfoxide-zinc.labels" $ | nindent 4 }}
  annotations: {{- include "sulfoxide-zinc.annotations" $ | nindent 4 }}
spec:
  acme:
    email: "{{ $v.email }}"
    server: "{{ $v.server}}"
    privateKeySecretRef:
      name: "{{ $.Release.Name }}-{{ $k }}-issuer"
    solvers:
      {{- toYaml $v.solvers | nindent 4 }}
      selector:
        dnsZones:
          {{- range $v.zones }}
          - {{ . }}
          {{ end }}
{{- end }}