{{ range $k, $v := .Values.issuers }}
{{- if $v.secrets.external.enable }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $.Release.Name -}}-external-secret
  annotations: {{- include "sulfoxide-zinc.annotations" $ | nindent 4 }}
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-2"
  labels: {{- include "sulfoxide-zinc.labels" $ | nindent 4 }}
spec:
  refreshInterval: {{ $v.secrets.external.refreshInterval }}
  secretStoreRef:
    name: {{ $v.secrets.external.secretStore.name }}
    kind: {{ $v.secrets.external.secretStore.kind }}
  target:
    name: {{ $v.secrets.name }}
    creationPolicy: {{ $v.secrets.external.policy.creation }}
    deletionPolicy: {{ $v.secrets.external.policy.deletion }}
  data:
    - secretKey: {{ $v.secrets.key }}
      remoteRef:
        key: "{{ $v.secrets.external.remoteSecretName }}"
---
{{- end }}
{{- if $v.secrets.internal.enable }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $v.secrets.name }}
  annotations: {{- include "sulfoxide-zinc.annotations" $ | nindent 4 }}
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-2"
  labels: {{- include "sulfoxide-zinc.labels" $ | nindent 4 }}
data:
  {{ $v.secrets.key }}: {{ b64enc $v.secrets.internal.value }}
---
{{- end }}
{{- end }}
