apiVersion: k3d.io/v1alpha4
kind: Simple
metadata:
  name: lapras
servers: 1
agents: 0
network: lapras
image: rancher/k3s:v1.25.12-k3s1
ports:
  - port: 20010:80
    nodeFilters:
      - loadbalancer
  - port: 20011:443
    nodeFilters:
      - loadbalancer
registries:
  create:
    name: lapras.registry.lvh.me
    host: "0.0.0.0"
    hostPort: "20012"
