name: CI-CD

on:
  push:

jobs:
  precommit:
    name: Pre-commit Check
    runs-on:
      - nscloud-ubuntu-22.04-amd64-4x8-with-cache
      - nscloud-cache-size-50gb
      - nscloud-cache-tag-sulfoxide-zinc-nix-store-cache
      - nscloud-git-mirror-1gb
    steps:
      - uses: AtomiCloud/actions.setup-nix@v1.3.1
      - name: Run pre-commit
        run: nix develop .#ci -c ./scripts/ci/pre-commit.sh

  release:
    name: Semantic Release
    needs:
      - precommit
    if: github.ref == 'refs/heads/main'
    runs-on:
      - nscloud-ubuntu-22.04-amd64-4x8-with-cache
      - nscloud-cache-size-50gb
      - nscloud-cache-tag-sulfoxide-zinc-releaser-nix-store-cache
      - nscloud-git-mirror-1gb
    steps:
      - uses: AtomiCloud/actions.setup-nix@v1.3.1
      - uses: AtomiCloud/actions.cache-npm@v1.0.1
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: nix develop .#releaser -c scripts/ci/release.sh
